// This file is auto-generated by Lovable. Do not modify it.
// Modified: Capacitor-safe OAuth — uses Supabase native OAuth + in-app browser
// to prevent auth flows from opening external Safari (Apple Guideline 4.0).

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
import { platform } from "@/lib/platform";

const lovableAuth = createLovableAuth({});

/**
 * In Capacitor, open the OAuth URL in the in-app browser and wait for the
 * deep-link callback that carries the auth tokens back into the WebView.
 */
async function signInWithOAuthNative(provider: "google" | "apple") {
  try {
    const { Browser } = await import("@capacitor/browser");
    const { App: CapApp } = await import("@capacitor/app");

    // Ask Supabase for the OAuth URL but don't redirect the WebView
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: `${window.location.origin}/login`,
        skipBrowserRedirect: true,
      },
    });

    if (error || !data.url) {
      return { error: error ?? new Error("No OAuth URL returned") };
    }

    // Open the OAuth page inside the Capacitor in-app browser overlay
    await Browser.open({ url: data.url, toolbarColor: "#0a1628" });

    // Wait for the app to receive a deep-link callback with the auth tokens
    return new Promise<{ error: Error | null }>((resolve) => {
      let listenerHandle: Awaited<ReturnType<typeof CapApp.addListener>> | null = null;

      const cleanup = async () => {
        if (listenerHandle) {
          listenerHandle.remove();
          listenerHandle = null;
        }
        await Browser.close().catch(() => {});
      };

      const timeout = setTimeout(async () => {
        await cleanup();
        resolve({ error: new Error("Sign in timed out") });
      }, 120_000);

      CapApp.addListener("appUrlOpen", async ({ url }) => {
        try {
          const urlObj = new URL(url);
          const hasTokens =
            urlObj.hash.includes("access_token") ||
            urlObj.search.includes("code=");

          if (!hasTokens) return; // Not our callback

          clearTimeout(timeout);
          await cleanup();

          window.location.href = `/login${urlObj.hash || `?${urlObj.searchParams.toString()}`}`;
          resolve({ error: null });
        } catch {
          // Not our URL — ignore
        }
      }).then((handle) => {
        listenerHandle = handle;
      });
    });
  } catch (e) {
    return { error: e instanceof Error ? e : new Error(String(e)) };
  }
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: { redirect_uri?: string }) => {
      // When running inside Capacitor, bypass the Lovable popup/redirect flow
      // and use Supabase OAuth + the in-app browser instead.
      if (platform.isNative) {
        return signInWithOAuthNative(provider);
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
