// Originally generated by Lovable. Rewritten 2026-05-08 after detaching from
// Lovable Cloud — the @lovable.dev/cloud-auth-js SDK pointed at /~oauth/initiate
// on Lovable's hosted endpoints, which no longer exist for this project.
//
// Web + native OAuth now go directly through Supabase Auth. The export shape
// (lovable.auth.signInWithOAuth) is preserved so Login.tsx/Signup.tsx don't
// need to change.

import { supabase } from "../supabase/client";
import { platform } from "@/lib/platform";

type OAuthOpts = { redirect_uri?: string };
type OAuthResult = { error: Error | null };

/**
 * In Capacitor, open the OAuth URL in the in-app browser and wait for the
 * deep-link callback that carries the auth tokens back into the WebView.
 * Avoids opening external Safari (Apple Guideline 4.0).
 */
async function signInWithOAuthNative(
  provider: "google" | "apple",
  opts: OAuthOpts = {}
): Promise<OAuthResult> {
  try {
    const { Browser } = await import("@capacitor/browser");
    const { App: CapApp } = await import("@capacitor/app");

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: opts.redirect_uri ?? `${window.location.origin}/login`,
        skipBrowserRedirect: true,
      },
    });

    if (error || !data?.url) {
      return { error: error ?? new Error("No OAuth URL returned") };
    }

    await Browser.open({ url: data.url, toolbarColor: "#0a1628" });

    return new Promise<OAuthResult>((resolve) => {
      let listenerHandle: Awaited<ReturnType<typeof CapApp.addListener>> | null = null;

      const cleanup = async () => {
        if (listenerHandle) {
          listenerHandle.remove();
          listenerHandle = null;
        }
        await Browser.close().catch(() => {});
      };

      const timeout = setTimeout(async () => {
        await cleanup();
        resolve({ error: new Error("Sign in timed out") });
      }, 120_000);

      CapApp.addListener("appUrlOpen", async ({ url }) => {
        try {
          const urlObj = new URL(url);
          const hasTokens =
            urlObj.hash.includes("access_token") ||
            urlObj.search.includes("code=");

          if (!hasTokens) return; // Not our callback

          clearTimeout(timeout);
          await cleanup();

          window.location.href = `/login${urlObj.hash || `?${urlObj.searchParams.toString()}`}`;
          resolve({ error: null });
        } catch {
          // Not our URL — ignore
        }
      }).then((handle) => {
        listenerHandle = handle;
      });
    });
  } catch (e) {
    return { error: e instanceof Error ? e : new Error(String(e)) };
  }
}

/**
 * Web OAuth flow: Supabase redirects the browser to the provider's consent
 * screen, then back to redirectTo with the session in the URL hash.
 * AuthContext.onAuthStateChange picks it up on the next page load.
 */
async function signInWithOAuthWeb(
  provider: "google" | "apple",
  opts: OAuthOpts = {}
): Promise<OAuthResult> {
  const { error } = await supabase.auth.signInWithOAuth({
    provider,
    options: {
      redirectTo: opts.redirect_uri ?? `${window.location.origin}/login`,
    },
  });
  return { error: error ?? null };
}

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple",
      opts?: OAuthOpts
    ): Promise<OAuthResult> => {
      // Apple is intentionally not configured at the destination Supabase
      // project (no external_apple_client_id/secret). Fail loud here rather
      // than letting Supabase return an opaque "provider not enabled" error.
      if (provider === "apple") {
        return {
          error: new Error(
            "Apple sign-in is not yet configured for this deployment."
          ),
        };
      }

      if (platform.isNative) {
        return signInWithOAuthNative(provider, opts);
      }

      return signInWithOAuthWeb(provider, opts);
    },
  },
};
